// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhnctdbfzyqmorfoudbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlobmN0ZGJmenlxbW9yZm91ZGJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTI3OTksImV4cCI6MjA2OTQ2ODc5OX0.up3LBJwfSjfBua2aLX1xjar4P3h-Ly_IOzUQfP6FVkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});